#!/usr/bin/env sh
#yabai -m config status_bar                   on
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
# global settings

yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.065
yabai -m config active_window_opacity        1
yabai -m config normal_window_opacity        0.88
yabai -m config window_border                on
yabai -m config window_border_width          7
yabai -m config window_placement             second_child
#yabai -m config active_window_border_color   0xff88C0D0 #nord light blue
#yabai -m config active_window_border_color   0xff83a598 #gruv blue
yabai -m config active_window_border_color   0xff98971a #gruv greenish
#yabai -m config active_window_border_color   0xffECEFF4
#yabai -m config normal_window_border_color   0xff88C0D0
yabai -m config normal_window_border_color   0x00ffffff
yabai -m config window_animation_duration 0.35
yabai -m config insert_feedback_color        0xffd75f5f

# Mouse Modifiers 
yabai -m config mouse_modifier cmd
yabai -m config mouse_action1              resize
yabai -m config mouse_action2              move
yabai -m config mouse_drop_action          swap
yabai -m config focus_follows_mouse       autoraise


yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 7 --label seven


# float system preferences| makes yabai ignore some stuff
yabai -m rule --add app="^Karabiner-EventViewer$"   manage=off
yabai -m rule --add app="^Finder$"   manage=off
yabai -m rule --add app="^preview$"   manage=off
yabai -m rule --add app="^Koodo Reader"   manage=off
yabai -m rule --add app="^Microsoft Word"   manage=off
yabai -m rule --add app="VLC"   manage=off
yabai -m rule --add app="^Spek"   manage=off
yabai -m rule --add app="Archive Utility"   manage=off
yabai -m rule --add app="GIMP-2.10" manage=off
yabai -m rule --add app="Ibooks"   manage=off
yabai -m rule --add app="Acrobat Reader"   manage=off
#yabai -m rule --add app="calibre"   manage=off
yabai -m rule --add app="clementine"   manage=off
yabai -m rule --add app="System Preferences"  manage=off
yabai -m rule --add app="Anki"  manage=off
yabai -m rule --add app="^Spotify$" space=2
yabai -m rule --add app="^Alacritty$" 
yabai -m rule --add app="^Brave Browser$" space=3
 
# assigning apps to spaces yahhh
yabai -m space 4 --label code #desktop 3
yabai -m config --space code top_padding 0
yabai -m config --space code bottom_padding 0
yabai -m config --space code left_padding 0
yabai -m config --space code right_padding 0
yabai -m config --space code window_gap 0

# Launcher terminal
yabai -m rule --add title="popuplauncher" manage=off sticky=on layer=above border=off
yabai -m rule --add title="configterm" manage=on sticky=off 

# general space settings
yabai -m config layout                       bsp
#yabai -m config top_padding                  50
#yabai -m config bottom_padding               10
#yabai -m config left_padding                 12
#yabai -m config right_padding                12
#yabai -m config window_gap                   6

yabai -m config left_padding                 60
yabai -m config right_padding                60
yabai -m config top_padding                  40
yabai -m config bottom_padding               40
yabai -m config window_gap                   20
# if status bar is on the bottom then the value should be 50
#yabai -m config external_bar main:20:65 #if bar is the transparent rounded one
#
#yabai -m config external_bar main:20:50 #my main bar
#
#Limelight addon (Kill it and start it each time Yabai starts)
#killall limelight &>/dev/null
#limelight &>/dev/null &


echo "yabai configuration loaded.. mybro"


